<a href="https://colab.research.google.com/github/arpitad001/Data-Science-course/blob/main/DataScience_Arpita_ipyp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Pyhton Zip Example
l1=[1,2,3]
l2=[4,5,6]
list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6)]

In [ ]:
#Using Pyhton Lists
import numpy as np
import time
size=1_000_000
l1=list(range(size))
l2=list(range(size))
start=time.time()
add=[x+y for x , y in zip(l1,l2)]
end=time.time()
print(add[0:10])
print(end-start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.08208727836608887


In [ ]:
#Using Numpy Arrays
import numpy as np
import time
size=1_000_000
l1=np.array(list(range(size)))
l2=np.array(list(range(size)))
start=time.time()
add=l1+l2
end=time.time()
print(add[0:10])
print(end-start)

[ 0  2  4  6  8 10 12 14 16 18]
0.002350330352783203


In [ ]:
#Creating Numpy Arrays
import numpy as np
arr1=np.array([1,2,3])  #1D Array
print(arr1)
arr2=np.array([[1,2,3],[4,5,6]])   #2D Array
print(arr2)


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
type(arr1)
type(arr2)

numpy.ndarray

In [ ]:
arr2.shape

(2, 3)

In [ ]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [ ]:
#creating arrays from scratch
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [ ]:
# Generate identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.arange(1,100 , 19)

array([ 1, 20, 39, 58, 77, 96])

In [ ]:
np.linspace(1, 100 , 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [ ]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
myarr.shape

(4, 3)

In [ ]:
myarr.size

12

In [ ]:
myarr.ndim

2

In [ ]:
myarr.dtype

dtype('int64')

In [ ]:
myarr.astype('float32')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [ ]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
reshape=myarr.reshape((3,4))
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [2]:
#Indexing and slicing
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
flat=arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
flat[0]

np.int64(1)

In [9]:
flat[3:6]

array([4, 5, 6])

In [10]:
flat[:5]  #same as flat[0:5]

array([1, 2, 3, 4, 5])

In [11]:
flat[3:]   #same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
flat[::2]  #every second element

array([ 1,  3,  5,  7,  9, 11])

In [15]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
b=flat[3:7].copy()  #This is not a slice because we are using copy method to get the copy
b

array([44444,     5,     6,     7])

In [20]:
b[0]=4444466
b

array([4444466,       5,       6,       7])

In [21]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          10,    11,    12])

In [22]:
# Fancy indexing(select multiple element)
arr=np.array([1,54,32,6,78,5,9,54,60,80,3])
arr[[1,4,8]]

array([54, 78, 60])

In [29]:
#Boolean masking(Filter data)
arr=np.array([1,54,32,6,78,5,9,54,60,80,3])
arr[arr>3]
#This is a powerful way to filter large datasets efficiently

array([54, 32,  6, 78,  5,  9, 54, 60, 80])

In [30]:
#Axes in a 2D array
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr[0]

array([1, 2, 3])

In [35]:
np.sum(arr,axis=0)  #column wise sum

array([12, 15, 18])

In [36]:
np.sum(arr,axis=1)   #row wise sum

array([ 6, 15, 24])

In [38]:
#Indexing in multidimensional arrays
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [39]:
#Indexing in 3D Array
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
print(arr3D.shape)

(2, 2, 3)


In [40]:
print(arr3D[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [41]:
#Selecting Data Along Axes
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)

[1 4 7]


In [42]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


In [43]:
# Changing Data Along an Axis
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
