<a href="https://colab.research.google.com/github/arpitad001/Data-Science-course/blob/main/DataScience_Arpita_ipyp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#Pyhton Zip Example
l1=[1,2,3]
l2=[4,5,6]
list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6)]

In [8]:
#Using Pyhton Lists
import numpy as np
import time
size=1_000_000
l1=list(range(size))
l2=list(range(size))
start=time.time()
add=[x+y for x , y in zip(l1,l2)]
end=time.time()
print(add[0:10])
print(end-start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.08208727836608887


In [11]:
#Using Numpy Arrays
import numpy as np
import time
size=1_000_000
l1=np.array(list(range(size)))
l2=np.array(list(range(size)))
start=time.time()
add=l1+l2
end=time.time()
print(add[0:10])
print(end-start)

[ 0  2  4  6  8 10 12 14 16 18]
0.002350330352783203


In [15]:
#Creating Numpy Arrays
import numpy as np
arr1=np.array([1,2,3])  #1D Array
print(arr1)
arr2=np.array([[1,2,3],[4,5,6]])   #2D Array
print(arr2)


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [18]:
type(arr1)
type(arr2)

numpy.ndarray

In [23]:
arr2.shape

(2, 3)

In [24]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [27]:
#creating arrays from scratch
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.full((3,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [32]:
# Generate identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.arange(1,100 , 19)

array([ 1, 20, 39, 58, 77, 96])

In [34]:
np.linspace(1, 100 , 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [35]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
myarr.shape

(4, 3)

In [38]:
myarr.size

12

In [39]:
myarr.ndim

2

In [40]:
myarr.dtype

dtype('int64')