<a href="https://colab.research.google.com/github/arpitad001/Data-Science-course/blob/main/DataScience_Arpita_ipyp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Pyhton Zip Example
l1=[1,2,3]
l2=[4,5,6]
list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6)]

In [ ]:
#Using Pyhton Lists
import numpy as np
import time
size=1_000_000
l1=list(range(size))
l2=list(range(size))
start=time.time()
add=[x+y for x , y in zip(l1,l2)]
end=time.time()
print(add[0:10])
print(end-start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.08208727836608887


In [ ]:
#Using Numpy Arrays
import numpy as np
import time
size=1_000_000
l1=np.array(list(range(size)))
l2=np.array(list(range(size)))
start=time.time()
add=l1+l2
end=time.time()
print(add[0:10])
print(end-start)

[ 0  2  4  6  8 10 12 14 16 18]
0.002350330352783203


In [ ]:
#Creating Numpy Arrays
import numpy as np
arr1=np.array([1,2,3])  #1D Array
print(arr1)
arr2=np.array([[1,2,3],[4,5,6]])   #2D Array
print(arr2)


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
type(arr1)
type(arr2)

numpy.ndarray

In [ ]:
arr2.shape

(2, 3)

In [ ]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [ ]:
#creating arrays from scratch
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [ ]:
# Generate identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.arange(1,100 , 19)

array([ 1, 20, 39, 58, 77, 96])

In [ ]:
np.linspace(1, 100 , 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [ ]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
myarr.shape

(4, 3)

In [ ]:
myarr.size

12

In [ ]:
myarr.ndim

2

In [ ]:
myarr.dtype

dtype('int64')

In [ ]:
myarr.astype('float32')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [ ]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
reshape=myarr.reshape((3,4))
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#Indexing and slicing
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
flat=arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
flat[0]

np.int64(1)

In [ ]:
flat[3:6]

array([4, 5, 6])

In [ ]:
flat[:5]  #same as flat[0:5]

array([1, 2, 3, 4, 5])

In [ ]:
flat[3:]   #same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
flat[::2]  #every second element

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b=flat[3:7].copy()  #This is not a slice because we are using copy method to get the copy
b

array([44444,     5,     6,     7])

In [ ]:
b[0]=4444466
b

array([4444466,       5,       6,       7])

In [ ]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          10,    11,    12])

In [ ]:
# Fancy indexing(select multiple element)
arr=np.array([1,54,32,6,78,5,9,54,60,80,3])
arr[[1,4,8]]

array([54, 78, 60])

In [ ]:
#Boolean masking(Filter data)
arr=np.array([1,54,32,6,78,5,9,54,60,80,3])
arr[arr>3]
#This is a powerful way to filter large datasets efficiently

array([54, 32,  6, 78,  5,  9, 54, 60, 80])

In [ ]:
#Axes in a 2D array
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0]

array([1, 2, 3])

In [ ]:
np.sum(arr,axis=0)  #column wise sum

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1)   #row wise sum

array([ 6, 15, 24])

In [ ]:
#Indexing in multidimensional arrays
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
#Indexing in 3D Array
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
print(arr3D.shape)

(2, 2, 3)


In [ ]:
print(arr3D[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [ ]:
#Selecting Data Along Axes
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)

[1 4 7]


In [ ]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


In [ ]:
# Changing Data Along an Axis
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]


In [44]:
#Data Types
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int64


In [45]:
#Changing data types
arr.astype("float64")

array([1., 2., 3., 4., 5.])

In [46]:
#Downcasting to save memory
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_small = arr_large.astype(np.int32)  # Downcasting to a smaller dtype
print(arr_small)
print(arr_small.dtype)

[1000000 2000000 3000000]
int32


In [47]:
#Memory usage(using n bytes method)
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
print(arr_int64.nbytes)
print(arr_int32.nbytes)

24
12


In [48]:
#Complex Numbers
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [49]:
#Object data types
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)  #It secrifices performance

print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']


Broadcasting in NumPy

In [52]:
#Looping over arrays in Python
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
result = []
for num in arr:
    result.append(num ** 2)
print(result)

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [53]:
#Vectorized Operation
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2  # Vectorized operation
print(result)

[ 1  4  9 16 25]


In [54]:
#Broadcasting with Scalar
result + 10

array([11, 14, 19, 26, 35])

In [55]:
#Broadcasting with arrays of different shapes
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2
print(result)

[11 22 33]


In [56]:
#Broadcasting a 2D array and a 1D Array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
result = arr1 + arr2
print(result)

[[2 4 6]
 [5 7 9]]


In [57]:
#Hands-on: Applying Broadcasting to Real-World Scenarios
#Normalizing Data Using Broadcasting
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])
mean = data.mean(axis=0)
std = data.std(axis=0)
normalized_data = (data - mean) / std
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [58]:
#Built in Mathematical Functions in NumPy
import numpy as np
arr=np.array([1,2,3,4,5])
np.mean(arr)

np.float64(3.0)

In [59]:
np.min(arr)

np.int64(1)

In [60]:
np.max(arr)

np.int64(5)

In [61]:
np.std(arr)

np.float64(1.4142135623730951)

In [62]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [63]:
np.diff(arr)

array([1, 1, 1, 1])

In [64]:
np.sum(arr)

np.int64(15)

In [65]:
np.median(arr)

np.float64(3.0)

In [66]:
np.argmin(arr)

np.int64(0)